version: "3"
services:
  app:
    container_name: user_microservice
    build: "."
    ports:
      - 5001:5000
    restart: always
    depends_on: 
      - user_postgresql

  user_postgresql:
    container_name: userdb_microservice
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
      - DATABASE_HOST=user-microservice
    ports:
      - "5432:5432"
    volumes:
      - ./db/user_table.sql:/docker-entrypoint-initdb.d/1-tables.sql