name: Fiuber User Microservice CI
on: push
jobs:
  check-linter:
    runs-on: ubuntu-latest
    name: Check Linter and Format
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm ci
      - run: npm run lint
  
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm ci
      - run: npm run test
  
  coverage:
    runs-on: ubuntu-latest
    name: Run coverage 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
    
      - run: npm ci
      - name: Run Coverage
        run: npm run coverage
      
      - name: Generate Coverage Report
        run: npm run report-coverage
        
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
